name: trigger_axon_56_510

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      GitUrlForAxon:
        description: 'Axon -git url'
        default: 'https://github.com/nervosnetwork/axon.git'
      GitBranchForAxon:
        description: 'axon  -git branch'
        default: 'main'
      StartAxon:
        description: 'start axon'
        default: 'true'



jobs:
  contract-tests:
    strategy:
      fail-fast: false
      matrix:
        net: ['testnet_v1']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Node Cache
        uses: actions/cache@v2
        id: npm-and-yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('/home/runner/work/**/package-lock.json', '/home/runner/work/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Deploy Local Network of Axon
        run: |
          if [ ${{ github.event.inputs.StartAxon }} == "true" ];then
             git clone -b ${{ github.event.inputs.GitBranchForAxon }} ${{ github.event.inputs.GitUrlForAxon }}
             cd axon
             cargo build --release
             rm -rf ./devtools/chain/data
             ./target/release/axon --config=./devtools/chain/config.toml --genesis=./devtools/chain/genesis_single_node.json > chain.log 2>&1 &
          fi
      - name: Run prepare
        id: runtest
        run: |
          npm install
          npm run test:init
      - name: Run test 56
        if: success() || failure()
        run: |
          npm run test:run56      
      - name: Run test 57
        if: success() || failure()
        run: |
          npm run test:run57      
      - name: Run test 58
        if: success() || failure()
        run: |
          npm run test:run58  
      - name: Run test 59
        if: success() || failure()
        run: |
          npm run test:run59
      - name: Run test 510
        if: success() || failure()
        run: |
          npm run test:run510
      - name: check axon status
        if: success() || failure()
        run: |
          curl http://localhost:8000 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params": [],"id":1}'
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: mochawesome-report/
